export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const PRODUCT_START = 'PRODUCT_START';
export const SINGLE_PRODUCT_LOADING = 'SINGLE_PRODUCT_LOADING';
export const SINGLE_PRODUCT_ERROR = 'SINGLE_PRODUCT_ERROR';
export const SINGLE_PRODUCT_START = 'SINGLE_PRODUCT_START';
